[package]
name = "hids-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
hids-common = { path = "../hids-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "hids"
path = "src/main.rs"
